services:
  mysql:
    image: mysql:8.0
    container_name: anjinma-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: anjinma
      MYSQL_USER: anjinma
      MYSQL_PASSWORD: anjinma

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf:/etc/mysql/conf.d

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot1234" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  anjinma-network:

volumes:
  mysql_data:
